# Generated by Django 4.1.4 on 2023-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='deviceId',
            field=models.CharField(max_length=500),
        ),
    ]
