# Generated by Django 4.1.4 on 2023-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usertoken_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='dateAdded',
            field=models.DateTimeField(),
        ),
    ]
