# Generated by Django 4.1.4 on 2023-01-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usertoken_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
