# Generated by Django 4.1.4 on 2023-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usertoken_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
