# Generated by Django 4.1.4 on 2022-12-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='image',
        ),
    ]
