# Generated by Django 4.1.4 on 2022-12-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0002_rename_img_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='banner',
            new_name='image',
        ),
    ]
