# Generated by Django 4.1.4 on 2022-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targetManagement", "0003_rename_banner_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="availability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="availability",
            field=models.BooleanField(default=False),
        ),
    ]
