# Generated by Django 4.1.4 on 2023-01-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0004_category_availability_item_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='img/cats'),
        ),
    ]
