# Generated by Django 4.1.4 on 2023-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0008_season_banner_category_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
