# Generated by Django 4.1.4 on 2023-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0011_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
