# Generated by Django 4.1.4 on 2023-01-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0012_banner_ismain'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='buttonAlign',
            field=models.CharField(default='left', max_length=20),
        ),
    ]
