# Generated by Django 4.1.4 on 2023-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0015_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
