# Generated by Django 4.1.4 on 2023-01-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0017_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
