# Generated by Django 4.1.4 on 2023-01-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0023_product_availability_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
