# Generated by Django 4.1.4 on 2023-02-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetManagement', '0028_category_ui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='season',
        ),
        migrations.AddField(
            model_name='banner',
            name='tags',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
